version: '3'
services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=pol
      - MONGO_PASSWORD=12qwaszxasqw12
      
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pol
      - MONGO_INITDB_ROOT_PASSWORD=12qwaszxasqw12