version: '3'
services:
  haproxy: 
    ports:
      - '80:80'
      - '8404:8404' 
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js