version: '3'
services:
  haproxy: 
    ports:
      - '3000:8083'
      - '8404:8404'
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=pol
      - MONGO_PASSWORD=12qwaszxasqw12
      - SESSION_SECRET=secret
        
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pol
      - MONGO_INITDB_ROOT_PASSWORD=12qwaszxasqw12
  
